version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      artifacts:
        patterns:
          - actions/upload-artifact
          - actions/download-artifact
  - package-ecosystem: npm
    directory: /infra
    schedule:
      interval: weekly
    groups:
      cdk:
        patterns:
          - aws-cdk
          - aws-cdk-lib
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
