name: Build Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - infra/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build lambdas
    runs-on: namespace-profile-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ~/.cabal
            ~/.local/share/mise
            ~/.ghcup
            ~/.npm
            ./infra/node_modules
      - uses: jdx/mise-action@v2
        with:
          experimental: true
          cache: false
      - name: Cabal build
        run: |
          cabal update
          cabal build cisserver
          cp $(cabal list-bin cisserver) out/bootstrap
      - uses: actions/upload-artifact@v4
        with:
          name: cisserver-${{ github.sha }}
          path: out/bootstrap
          if-no-files-found: error
