name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - infra/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: namespace-profile-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: |
          cabal build cisserver --enable-executable-static
          cp $(cabal list-bin cisserver) out/bootstrap
      - uses: actions/upload-artifact@v4
        with:
          name: cisserver-${{ github.sha }}
          path: out/bootstrap

  deploy:
    runs-on: namespace-profile-arm64
    needs:
      - build
    permissions:
      contents: read
      id-token: write
    environment:
      name: Production
      url: https://glenda.loveistheplan.net
    steps:
      - uses: actions/checkout@v4
      - uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ~/.cabal
            ~/.local/share/mise
            ~/.ghcup
            ~/.npm
            ./infra/node_modules
      - uses: jdx/mise-action@v2
        with:
          experimental: true
          cache: false
      - run: npm ci
        working-directory: infra
      - uses: actions/download-artifact@v4
        with:
          name: cisserver-${{ github.sha }}
          path: out/bootstrap
      - run: ls -l out
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::029230740929:role/GitHubDeploymentRole
      - if: github.ref_name != 'main'
        run: npm run cdk diff -- --all --require-approval=never
        working-directory: infra
      - if: github.ref_name == 'main'
        run: npm run cdk deploy -- --all --require-approval=never
        working-directory: infra
