name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-base:
    runs-on: buildjet-8vcpu-ubuntu-2204-arm
    permissions:
      packages: write
      contents: read
    steps:
      - run: |
          echo "uid=$(id -u)" >> "$GITHUB_OUTPUT"
        id: uid
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          file: ghc.Dockerfile
          push: true
          tags: ghcr.io/typeverity/ghc-base:latest
          cache-from: type=registry,ref=ghcr.io/typeverity/ghc-base:latest
          cache-to: type=inline
          build-args: |
            uid=${{ steps.uid.outputs.uid }}

  build:
    runs-on: buildjet-8vcpu-ubuntu-2204-arm
    needs:
      - build-base
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize cabal
        run: >
          mkdir -p ~/.cabal &&
          docker run --user glenda --rm -v ~/.cabal:/home/glenda/.cabal -v $PWD:/app -w /app ghcr.io/typeverity/ghc-base:latest
          cabal update

      - name: Configure the build
        run: >
          docker run --user glenda --rm -v ~/.cabal:/home/glenda/.cabal -v $PWD:/app -w /app ghcr.io/typeverity/ghc-base:latest
          sh -c 'cabal configure --enable-tests --enable-benchmarks --disable-documentation && cabal build --dry-run'
        # The last step generates dist-newstyle/cache/plan.json for the cache key.

      - name: Restore cached dependencies
        uses: buildjet/cache/restore@v3
        id: cache
        env:
          key: ${{ runner.os }}-${{ runner.arch }}-ghc-9.6.3
        with:
          path: ~/.cabal
          key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}-

      - name: Install dependencies
        run: >
          docker run --user glenda --rm -v ~/.cabal:/home/glenda/.cabal -v $PWD:/app -w /app ghcr.io/typeverity/ghc-base:latest
          cabal build all --only-dependencies

      # Cache dependencies already here, so that we do not have to rebuild them should the subsequent steps fail.
      - name: Save cached dependencies
        uses: buildjet/cache/save@v3
        # Caches are immutable, trying to save with the same key would error.
        if: ${{ steps.cache.outputs.cache-primary-key != steps.cache.outputs.cache-matched-key }}
        with:
          path: ~/.cabal
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - run: |
          docker run --user glenda --rm -v ~/.cabal:/home/glenda/.cabal -v $PWD:/app -w /app ghcr.io/typeverity/ghc-base:latest \
            sh -c 'cabal build cisserver --enable-executable-static && cp $(cabal list-bin cisserver) out/bootstrap'

      - uses: actions/upload-artifact@v3
        with:
          name: cisserver-${{ github.sha }}
          path: out/bootstrap

  deploy:
    runs-on: ubuntu-22.04
    needs:
      - build
    permissions:
      contents: read
      id-token: write
    environment:
      name: Production
      url: https://glenda.loveistheplan.net
    steps:
      - uses: actions/checkout@v4

      - uses: buildjet/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: infra/package-lock.json

      - run: npm ci
        working-directory: infra

      - uses: actions/download-artifact@v3
        with:
          name: cisserver-${{ github.sha }}
          path: out/bootstrap

      - run: ls -l out

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::029230740929:role/GitHubDeploymentRole

      - if: github.ref_name != 'main'
        run: npm run cdk diff -- --all --require-approval=never
        working-directory: infra

      - if: github.ref_name == 'main'
        run: npm run cdk deploy -- --all --require-approval=never
        working-directory: infra
