name: infra
on:
  pull_request:
    branches:
      - main
    paths:
      - infra/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  check-cdk:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: buildjet/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: infra/package-lock.json

      - run: npm ci
        working-directory: infra

      - run: npm run build
        working-directory: infra
